repos:
- repo: local
  hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]
      args: [--max-line-length=79]

    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      args: [--line-length=79, --target-version=py37]

    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]
